In [20]:
import pandas as pd
import numpy as np

In [21]:
Nike_df = pd.read_csv(r'D:\AI & ML\Libraries\Sir\Pandas\Practice_dataset\Nike_Sales_Uncleaned.csv')
Nike_df

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,NaN,0.0,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,L,-1.0,NaN,NaN,0.0,NaN,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.0,02-07-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,NaN,4.0,5358.70,NaN,0.0,11-12-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,NaN,0.0,23-11-2024,Retail,Mumbai,2453.57

## EDA

In [22]:
Nike_df.dtypes

Order_ID              int64
Gender_Category      object
Product_Line         object
Product_Name         object
Size                 object
Units_Sold          float64
MRP                 float64
Discount_Applied    float64
Revenue             float64
Order_Date           object
Sales_Channel        object
Region               object
Profit              float64
dtype: object

In [23]:
Nike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              1990 non-null   object
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 254.0+ KB

In [24]:
Nike_df.describe()

,Order_ID,Units_Sold,MRP,Discount_Applied,Revenue,Profit
count,2500.000000,1265.000000,1246.000000,832.000000,2500.000000,2500.000000
mean,3194.352400,1.482213,6039.863395,0.631022,274.873716,1376.012848
std,749.972638,1.696947,2315.746826,0.365500,2023.773550,1478.671013
min,2000.000000,-1.000000,2006.630000,0.000000,-7561.590000,-1199.450000
25%,2534.750000,0.000000,4038.902500,0.320000,0.000000,93.532500
50%,3192.500000,2.000000,6110.030000,0.615000,0.000000,1371.385000
75%,3841.250000,3.000000,8022.187500,0.962500,0.000000,2660.645000
max,4499.000000,4.000000,9996.220000,1.250000,37169.350000,3999.210000

In [25]:
Nike_df.isnull().sum()

Order_ID               0
Gender_Category        0
Product_Line           0
Product_Name           0
Size                 510
Units_Sold          1235
MRP                 1254
Discount_Applied    1668
Revenue                0
Order_Date           616
Sales_Channel          0
Region                 0
Profit                 0
dtype: int64

In [26]:
Nike_df.select_dtypes(include = 'number')

      Order_ID  Units_Sold      MRP  Discount_Applied  Revenue   Profit
0         2000         NaN      NaN              0.47      0.0  -770.45
1         2001         3.0  4957.93               NaN      0.0  -112.53
2         2002         4.0      NaN               NaN      0.0  3337.34
3         2003         NaN  9673.57               NaN      0.0  3376.85
4         2004         NaN      NaN               NaN      0.0   187.89
...        ...         ...      ...               ...      ...      ...
2495      4495         3.0      NaN               NaN      0.0     2.97
2496      4496        -1.0      NaN               NaN      0.0  -487.36
2497      4497         NaN  6647.60              0.52      0.0  -918.14
2498      4498         4.0  5358.70               NaN      0.0  3352.29
2499      4499         NaN  5550.99               NaN      0.0  2453.57

[2500 rows x 6 columns]

In [27]:
Nike_df.select_dtypes(include='number').columns

Index(['Order_ID', 'Units_Sold', 'MRP', 'Discount_Applied', 'Revenue',
       'Profit'],
      dtype='object')

In [28]:
col_list = ['Units_Sold', 'MRP', 'Discount_Applied', 'Revenue','Profit']

for i in col_list:
    Nike_df[i].fillna(Nike_df[i].mean(),inplace=True)

C:\Users\Harsh\AppData\Local\Temp\ipykernel_19860\877171095.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Nike_df[i].fillna(Nike_df[i].mean(),inplace=True)

In [29]:
Nike_df.isnull().sum()

Order_ID              0
Gender_Category       0
Product_Line          0
Product_Name          0
Size                510
Units_Sold            0
MRP                   0
Discount_Applied      0
Revenue               0
Order_Date          616
Sales_Channel         0
Region                0
Profit                0
dtype: int64

In [36]:
Nike_df['Size'].head(10)

0     M
1     M
2     M
3     L
4    XL
5     M
6     M
7     M
8    11
9     M
Name: Size, dtype: object

In [37]:
Nike_df['Size'].unique()

array(['M', 'L', 'XL', '11', nan, '9', '6', '12', '7', '10', '8'],
      dtype=object)

In [38]:
Nike_df['Size'].value_counts()

Size
L     513
XL    512
M     478
7      86
11     77
10     76
9      68
12     61
8      60
6      59
Name: count, dtype: int64

In [31]:
# Nike_df['Size'].fillna(Nike_df['Size'].mode()[0],inplace=True)
# Nike_df['Size'].isnull().sum()

In [32]:
Nike_df['Order_Date'] = pd.to_datetime(Nike_df['Order_Date'],format='mixed')

In [33]:
Nike_df['Order_Date'].ffill(inplace=True)
Nike_df['Order_Date'].isnull().sum()

C:\Users\Harsh\AppData\Local\Temp\ipykernel_19860\114281918.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Nike_df['Order_Date'].ffill(inplace=True)

0

In [34]:
Nike_df.isnull().sum()

Order_ID              0
Gender_Category       0
Product_Line          0
Product_Name          0
Size                510
Units_Sold            0
MRP                   0
Discount_Applied      0
Revenue               0
Order_Date            0
Sales_Channel         0
Region                0
Profit                0
dtype: int64

In [35]:
Nike_df.loc[55:90]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
55,2055,Men,Basketball,Kyrie Flytrap,L,1.482213,6039.863395,0.631022,0.00,2024-10-26,Online,hyderbad,-1078.76
56,2056,Men,Running,React Infinity,L,3.000000,6039.863395,0.631022,0.00,2024-05-31,Retail,Bangalore,-244.44
57,2048,Men,Lifestyle,Waffle One,M,3.000000,6216.290000,0.940000,1118.93,2024-09-14,Online,Mumbai,-642.02
58,2058,Women,Training,Flex Trainer,11,1.482213,4985.920000,0.631022,0.00,2024-09-14,Online,Kolkata,361.54
59,2059,Kids,Soccer,Phantom GT,NaN,-1.000000,9507.540000,0.631022,0.00,2023-12-27,Retail,Delhi,291.28
60,2060,Men,Lifestyle,Waffle One,L,2.000000,7979.260000,0.631022,0.00,2024-07-11,Online,bengaluru,2821.59
61,2061,Women,Basketball,LeBron 20,L,1.482213,6039.863395,0.631022,0.00,2024-10-09,Online,Mumbai,-501.68
62,2062,Men,Basketball,Air Jordan,NaN,2.000000,6039.863395,0.631022,0.00,2025-06-06,Online,Bangalore,1823.91
63,2063,Women,Basketball,Air Jordan,M,1.000000,9751.000000,0.160000,8190.84,2024-06-09,Retail,Pune,1130.31
64,2064,Kids,Running,React Infinity,L,2.000000,7557.710000,0.631022,0.00,2025-03-02,Online,Bangalore,3277.44
65,2065,Women,Lifestyle,Waffle One,10,1.482213,6039.863395,0.780000,0.00,2024-02-11,Retail,Hyd,21.58
66,2066,Men,Soccer,Phantom GT,XL,-1.000000,5259.050000,0.631022,0.00,2024-12-10,Online,Mumbai,1022.82
67,2067,Kids,Basketball,LeBron 20,L,4.000000,3588.380000,0.631022,0.00,2025-06-05,Online,Kolkata,161.50
68,2068,Men,Running,Free RN,NaN,4.000000,2553.290000,0.631022,0.00,2024-12-05,Retail,Mumbai,984.90
69,2069,Women,Training,SuperRep Go,NaN,1.482213,7502.240000,0.631022,0.00,2025-07-14,Online,Pune,3554.58
70,2070,Kids,Running,React Infinity,L,1.482213,6039.863395,0.631022,0.00,2025-07-14,Retail,Mumbai,1112.43
71,2071,Kids,Lifestyle,Blazer Mid,M,3.000000,7849.810000,0.490000,12010.21,2025-01-12,Retail,Pune,-882.96
72,2072,Men,Training,Flex Trainer,NaN,3.000000,6039.863395,0.631022,0.00,2025-01-12,Retail,Pune,3639.20
73,2073,Women,Lifestyle,Blazer Mid,12,4.000000,6039.863395,0.850000,0.00,2024-03-11,Online,Hyd,443.86
74,2074,Men,Training,Flex Trainer,L,-1.000000,6039.863395,0.570000,0.00,2024-03-11,Online,Kolkata,1958.47
75,2075,Kids,Basketball,Air Jordan,L,4.000000,4251.740000,0.631022,0.00,2025-07-14,Online,Pune,2345.35
76,2076,Women,Training,ZoomX Invincible,11,1.482213,6039.863395,0.631022,0.00,2024-10-13,Retail,bengaluru,2011.25
77,2077,Men,Training,ZoomX Invincible,L,1.482213,6039.863395,0.631022,0.00,2023-11-21,Online,Pune,3332.66
78,2078,Women,Basketball,LeBron 20,NaN,0.000000,6970.470000,0.631022,0.00,2023-11-21,Online,Mumbai,262.79
79,2079,Men,Running,Pegasus Turbo,XL,-1.000000,4322.060000,0.631022,0.00,2025-01-19,Online,bengaluru,279.78
80,2080,Men,Lifestyle,Blazer Mid,L,1.482213,6039.863395,0.631022,0.00,2025-03-31,Online,Bangalore,-1005.89
81,2081,Men,Training,ZoomX Invincible,L,1.482213,6039.863395,0.631022,0.00,2025-03-31,Online,Mumbai,2810.49
82,2028,Men,Running,Free RN,NaN,-1.000000,6039.863395,0.210000,0.00,2024-02-14,Online,Hyderabad,3303.01
83,2083,Men,Running,Free RN,NaN,1.482213,9291.740000,0.631022,0.00,2024-10-14,Retail,Delhi,-981.21
84,2084,Men,Training,Metcon 7,M,2.000000,6039.863395,0.631022,0.00,2023-12-24,Online,Mumbai,408.39
85,2085,Men,Basketball,Kyrie Flytrap,NaN,1.482213,7561.850000,0.631022,0.00,2024-12-17,Retail,Kolkata,98.72
86,2086,Men,Soccer,Mercurial Superfly,L,0.000000,6039.863395,0.450000,0.00,2024-10-11,Online,Kolkata,1742.66
87,2087,Kids,Basketball,Zoom Freak,NaN,1.482213,4656.280000,0.631022,0.00,2024-11-01,Online,Kolkata,3777.50
88,2088,Women,Running,Free RN,XL,4.000000,6039.863395,0.631022,0.00,2025-04-26,Online,Bangalore,2702.93
89,2089,Women,Training,Flex Trainer,L,2.000000,6874.770000,0.600000,5499.82,2024-02-12,Online,Mumbai,-1076.66
90,2090,Kids,Lifestyle,Dunk Low,8,1.482213,6039.863395,0.631022,0.00,2024-02-12,Retail,Bangalore,163.15